* HTML 5 reference

** Elemento Raíz

*** <!doctype html>

		Define que el documento esta bajo el estandar de HTML 5

*** <html>

		Representa la raíz de un documento HTML o XHTML. Todos los demás
		elementos deben ser descendientes de este elemento.

** Metadatos del documento

*** <head>
		Representa una colección de metadatos acerca del documento,
		incluyendo enlaces a, o definiciones de, scripts y hojas de
		estilo.

*** <title>

		Define el título del documento, el cual se muestra en la barra de
		título del navegador o en las pestañas de página. Solamente puede
		contener texto y cualquier otra etiqueta contenida no será
		interpretada.

*** <base>
		Define la URL base para las URLs relativas en la página.

*** <link>
		Usada para enlazar JavaScript y CSS externos con el documento HTML
		actual.

*** <meta>
		Define los metadatos que no pueden ser definidos usando otro
		elemento HTML.

*** <style>
		Etiqueta de estilo usada para escribir CSS en línea.

** Scripting

*** <script>
		Define ya sea un script interno o un enlace hacia un script
		externo.

		El lenguaje de programación es JavaScript

*** <noscript>
		Define un contenido alternativo a mostrar cuando el navegador no
		soporta scripting.

** Secciones

*** <body>

		Representa el contenido principal de un documento HTML. Solo hay
		un elemento <body> en un documento.

*** <section>

		[+ HTML5 ] 	Define una sección en un documento.

*** <nav>

		[+ HTML5 ] Define una sección que solamente contiene enlaces de
		navegación

*** <article>

		[+ HTML5 ] Define contenido autónomo que podría existir
		independientemente del resto del contenido.

*** <aside>

		[+ HTML5 ] Define algunos contenidos vagamente relacionados con el
		resto del contenido de la página. Si es removido, el contenido
		restante seguirá teniendo sentido

*** <h1>-<h6>

		Los elemento de cabecera implementan seis niveles de cabeceras de
		documentos; <h1> es la de mayor y <h6> es la de menor
		impotancia. Un elemento de cabecera describe brevemente el tema de
		la sección que introduce.

*** <header>

		[+ HTML5 ] Define la cabecera de una página o sección. Usualmente
		contiene un logotipo, el título del sitio Web y una tabla de
		navegación de contenidos.

*** <footer>

		[+ HTML5 ] Define el pie de una página o sección. Usualmente
		contiene un mensaje de derechos de autoría, algunos enlaces a
		información legal o direcciones para dar información de
		retroalimentación.

*** <address>

		Define una sección que contiene información de contacto.

*** <main>

		[+ HTML5 ] Define el contenido principal o importante en el
		documento.  Solamente existe un elemento <main> en el documento.

** Agrupación de Contenido

*** <p>

		Define una parte que debe mostrarse como un párrafo.

*** <hr>

		Representa un quiebre temático entre parrafos de una sección o
		articulo o cualquier contenido.

*** <pre>

		Indica que su contenido esta preformateado y que este formato debe
		ser preservado.

*** <blockquote>

		Representa una contenido citado desde otra fuente.

*** <ol>

		Define una lista ordenada de artículos.

*** <ul>

		Define una lista de artículos sin orden.

*** <li>

		Define un artículo de una lista ennumerada.

*** <dl>

		Define una lista de definiciones, es decir, una lista de términos
		y sus definiciones asociadas.

*** <dt>

		Representa un término definido por el siguiente <dd>.

*** <dd>

		Representa la definición de los terminos listados antes que él.

*** <figure>

		[+ HTML5 ] 	Representa una figura ilustrada como parte  del documento.

*** <figcaption>

		[+ HTML5 ] 	Representa la leyenda de una figura.

*** <div>

		Representa un contenedor genérico sin ningún significado especial.

** Semántica a nivel de Texto

*** <a>

		Representa un hiperenlace , enlazando a otro recurso.

*** <em>

		Representa un texto enfatizado , como un acento de intensidad.

*** <strong>

		Representa un texto especialmente importante .

*** <small>

		Representa un comentario aparte , es decir, textos como un
		descargo de responsabilidad o una nota de derechos de autoría, que
		no son esenciales para la comprensión del documento.

*** <s>

		Representa contenido que ya no es exacto o relevante .

*** <cite>

		Representa el título de una obra .

*** <q>

		Representa una cita textual  inline.

*** <dfn>

		Representa un término cuya definición está contenida en su
		contenido ancestro más próximo.

*** <abbr>

		Representa una abreviación o un acrónimo ; la expansión de la
		abreviatura puede ser representada por el atributo title.

*** <data>

		[+ HTML5 ] Asocia un equivalente legible por máquina a sus
		contenidos. (Este elemento está sólamente en la versión de la
		WHATWG del estandar HTML, y no en la versión de la W3C de HTML5).

*** <time>

		[+ HTML5 ] Representa un valor de fecha y hora; el equivalente
		legible por máquina puede ser representado en el atributo
		datetime.

*** <code>

		Representa un código de ordenador .

*** <var>

		Representa a una variable, es decir, una expresión matemática o
		contexto de programación, un identificador que represente a una
		constante, un símbolo que identifica una cantidad física, un

		parámetro de una función o un marcador de posición en prosa.

*** <samp>
		Representa la salida de un programa o un ordenador.

*** <kbd>

		Representa la entrada de usuario, por lo general desde un teclado,
		pero no necesariamente, este puede representar otras formas de
		entrada de usuario, como comandos de voz transcritos.

*** <sub>,<sup>

		Representan un subíndice y un superíndice, respectivamente.

*** <i>

		Representa un texto en una voz o estado de ánimo alterno, o por lo
		menos de diferente calidad, como una designación taxonómica, un
		término técnico, una frase idiomática, un pensamiento o el nombre
		de un barco.

*** <b>

		Representa un texto hacia el cual se llama la atención para
		propósitos utilitaros.  No confiere ninguna importancia adicional
		y no implica una voz alterna.

*** <u>

		Representa una anotación no textual sin-articular, como etiquetar
		un texto como mal escrito o etiquetar un nombre propio en texto en
		Chino.

*** <mark>

		[+ HTML5 ] Representa texto resaltado con propósitos de
		referencia, es decir por su relevancia en otro contexto.

*** <ruby>

		[+ HTML5 ] Representa contenidos a ser marcados con anotaciones
		ruby, recorridos cortos de texto presentados junto al texto. Estos
		son utilizados con regularidad en conjunto a lenguajes de Asia del
		Este, donde las anotaciones actúan como una guía para la
		pronunciación, como el furigana Japonés.

*** <rt>

		[+ HTML5 ]	Representa el texto de una anotación ruby .

*** <rp>

		[+ HTML5 ] Representa los paréntesis alrededor de una anotación
		ruby, usada para mostrar la anotación de manera alterna por los
		navegadores que no soporten despliegue estandar para las
		anotaciones.

*** <bdi>

		[+ HTML5 ] Representa un texto que debe ser aislado de sus
		alrededores para el formateado bidireccional del texto.  Permite
		incrustar un fragmento de texto con una direccionalidad diferente
		o desconocida.

*** <bdo>

		Representa la direccionalidad de sus descendientes con el fin de
		anular de forma explícita al algoritmo bidireccional Unicode.

*** <span>

		Representa texto sin un significado específico.  Este debe ser
		usado cuando ningún otro elemento semántico le confiere un
		significado adecuado, en cuyo caso, provendrá de atributos
		globales como class, lang, o dir.

*** <br>

		Representa un salto de línea.

*** <wbr>

		[+ HTML5 ] Representa una oportunidad de salto de línea, es decir,
		un punto sugerido de envoltura donde el texto de múltiples líneas
		puede ser dividido para mejorar su legibilidad.

** Ediciones

*** <ins>

		Define una adición en el documento.

*** <del>

		Define una remoción del documento.

** Contenido incrustado

*** <img>

		Representa una imagen.

*** <iframe>

		Representa un contexto anidado de navegación, es decir, un
		documento HTML embebido.

*** <embed>

		[+ HTML5 ] Representa un punto de integración para una aplicación
		o contenido interactivo externo que por lo general no es HTML.

*** <object>

		Representa un recurso externo, que será tratado como una imagen,
		un sub-documento HTML o un recurso externo a ser procesado por un
		plugin.

*** <param>

		Define parámetros para el uso por los plugins invocados por los
		elementos <object>.

*** <video>

		[+ HTML5 ] Representa un video , y sus archivos de audio y
		capciones asociadas, con la interfaz necesaria para reproducirlos.

*** <audio>

		[+ HTML5 ]	Representa un sonido o stream de audio.

*** <source>

		[+ HTML5 ] Permite a autores especificar recursos multimedia
		alternativos para los elementos multimedia como <video> o <audio>.

*** <track>

		[+ HTML5 ] Permite a autores especificar una pista de texto
		temporizado para elementos multimedia como <video> o <audio>.

*** <canvas>

		[+ HTML5 ] Representa un área de mapa de bits en el que se pueden
		utilizar scripts para renderizar gráficos como gráficas, gráficas
		de juegos o cualquier imagen visual al vuelo.

*** <map>

		En conjunto con <area>, define un mapa de imagen.

*** <area>
		En conjunto con  <map>, define un mapa de imagen.

*** <svg>

		[+ HTML5 ]	Define una imagen vectorial embebida.

*** <math>

		[+ HTML5 ]	Define una fórmula matemática.

** Datos tabulares

*** <table>

		Representa datos con más de una dimensión.

*** <caption>

		Representa el título de una tabla.

*** <colgroup>

		Representa un conjunto de una o más columnas de una tabla.

*** <col>

		Representa una columna de una tabla.

*** <tbody>

		Representa el bloque de filas que describen los datos contretos de
		una tabla.

*** <thead>

		Representa el bloque de filas que describen las etiquetas de
		columna de una tabla.

*** <tfoot>

		Representa los bloques de filas que describen los resúmenes de
		columna de una tabla.

*** <tr>

		Representa una fila de celdas en una tabla.

*** <td>

		Representa una celda de datos en una tabla.

*** <th>

		Representa una celda encabezado en una tabla.

** Formularios

*** <form>

		Representa un formulario, consistendo de controles que puede ser
		enviado a un servidor para procesamiento.

*** <fieldset>

		Representa un conjunto de controles.

*** <legend>

		Representa el título de un <fieldset>.

*** <label>

		Representa el título de un control de formulario.

*** <input>

		Representa un campo de datos escrito que permite al usuario editar
		los datos.

*** <button>

		Representa un botón .

*** <select>

		Representa un control que permite la selección entre un conjunto
		de opciones.

*** <datalist>

		[+ HTML5 ] Representa un conjunto de opciones predefiniddas para
		otros controles.

*** <optgroup>

		Representa un conjunto de opciones, agrupadas lógicamente.

*** <option>

		Representa una opción en un elemento <select>, o una sugerencia de
		un elemento <datalist>.

*** <textarea>

		Representa un control de edición de texto multi-línea.

*** <keygen>

		[+ HTML5 ] Representa un control de par generador de llaves.

*** <output>

		[+ HTML5 ] Representa el resultado de un cálculo.

*** <progress>

		[+ HTML5 ] Representa el progreso de finalización de una tarea.

*** <meter>

		[+ HTML5 ] Representa la medida escalar (o el valor fraccionario)
		dentro de un rango conocido.

** Elementos interactivos

*** <details>

		[+ HTML5 ] Representa un widget desde el que un usuario puede
		obtener información o controles adicionales.

*** <summary>

		[+ HTML5 ] Representa un resumen, título o leyenda para un
		elemento <details> dado.

*** <command>

		[+ HTML5 ] Representa un comando que un usuario puede invocar.

*** <menu>

		[+ HTML5 ]	Representa una lista de comandos.
